### ISSUE TITLE
Would you consider adding beancount-reds-plugins

### ISSUE THREAD

**Issue by bradrushworth** [tarioch/docker-fava#105]
These plugins are very useful to a general audience.

Plugin list:
[autoclose_tree](https://github.com/redstreet/beancount_reds_plugins/tree/master/beancount_reds_plugins/autoclose_tree#readme): automatically closes all of an account's descendants when an account is closed.
[capital_gains_classifier](https://github.com/redstreet/beancount_reds_plugins/tree/master/beancount_reds_plugins/capital_gains_classifier#readme): rebooks capital gains into separate long and short accounts, and separate gains and losses accounts
[effective_date](https://github.com/redstreet/beancount_reds_plugins/tree/master/beancount_reds_plugins/effective_date#readme): enables per-posting dates (each posting in a transaction can have a different date)
[opengroup](https://github.com/redstreet/beancount_reds_plugins/tree/master/beancount_reds_plugins/opengroup#readme): Inserts open statements for sets of accounts based on specifiable rules.
[rename_accounts](https://github.com/redstreet/beancount_reds_plugins/tree/master/beancount_reds_plugins/rename_accounts#readme): rename arbitrary accounts on the fly (eg: move Taxes from Expenses to Income when you temporarily want to view all your Expenses except taxes)
[zerosum](https://github.com/redstreet/beancount_reds_plugins/tree/master/beancount_reds_plugins/zerosum#readme): find matching pairs of postings that sum up to zero. Useful in de-duplication, and tracking things such as reimbursements, rebates, etc.

https://github.com/redstreet/beancount_reds_plugins

beancount-reds-plugins==0.3.0

**Comment by wangweitung** [comment]
Would you consider adding [fava-dashboards](https://github.com/andreasgerstmayr/fava-dashboards)?

**Comment by tarioch** [comment]
sure, feel free to create a pr, should basically just be to add it to the requirements file

**Comment by tarioch** [comment]
Just created it for you, try the latest image

**Comment by wangweitung** [comment]
> Just created it for you, try the latest image

Thx!
